trigger:
  branches:
    include:
      - main
      - refs/tags/v*
      
pool:
  vmImage: windows-latest  

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  fetchDepth: 0
  clean: true

- task: gitversion/setup@3.1.11
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.11.x'
      
- task: gitversion/execute@3.1.11
  displayName: Execute GitVersion

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  
- task: PowerShell@2
  displayName: Install OVS
  condition: true
  inputs:
    pwsh: true
    targetType: 'inline'
    script: |
      # Expand-Archive is a script module and will take its preferences from the global scope.
      # See https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/77#issuecomment-601947496
      $global:ProgressPreference = 'SilentlyContinue'
      
      Invoke-WebRequest -Uri 'https://github.com/eryph-org/eryph/raw/refs/heads/main/ovspackage.zip' -OutFile C:\ovspackage.zip -UseBasicParsing
      Expand-Archive -Path C:\ovspackage.zip -DestinationPath C:\openvswitch\usr

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"  --no-build'
  
- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    nobuild: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)  --no-build'
    
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: build-packages

- task: NuGetCommand@2
  displayName: publish to project nuget repo
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '59a3608a-9bed-4cb4-9467-6efaaa3cbef5/1e425ef4-e3a0-4927-b4c0-2beff753cb88'  
